import libs = libsdl3%lib{sdl3}

# Demonstrative program, not an automated test: building it is enough, do
# not try to launch a windowed/camera program headlessly.
#
exe{*}: test = false

./: exe{camera-read-and-draw}: c{01-read-and-draw/read-and-draw} $libs

c.poptions =+ "-I$out_root" "-I$src_root"
