import libs = libsdl3%lib{sdl3}

./: exe{input-joystick-polling}: c{01-joystick-polling/joystick-polling} $libs
./: exe{input-joystick-events}:  c{02-joystick-events/joystick-events}   $libs
./: exe{input-gamepad-polling}:  c{03-gamepad-polling/gamepad-polling}   $libs
./: exe{input-gamepad-events}:   c{04-gamepad-events/gamepad-events}     $libs

c.poptions =+ "-I$out_root" "-I$src_root"

# Runtime resource upstream's own build copies next to this executable
# (upstream/examples/CMakeLists.txt DATAFILES).
#
exe{input-gamepad-polling}: file{gamepad_front.png}: include = adhoc

# Install next to the executable that uses it.
#
file{gamepad_front.png}@./: install = $install.bin
