# Public headers under SDL3/.
#
pub_hdrs = SDL3/h{**}

./: $pub_hdrs

# Install into include/SDL3/ (headers already live in SDL3/ subdir of prefix).
#
SDL3/h{*}:
{
  install         = include/SDL3/
  install.subdirs = true
}

# Private build_config (templates / static platform configs). Not installed.
#
build_config/: install = false
