# Public headers under SDL3/.
#
pub_hdrs = SDL3/h{**}

# Private build_config: templates and static platform configs. Distributed
# with the package (needed to generate the private config header) but not
# installed for consumers.
#
priv_cfg = build_config/file{**}

./: $pub_hdrs $priv_cfg

# Install into include/SDL3/ (headers already live in SDL3/ subdir of prefix).
#
SDL3/h{*}:
{
  install         = include/SDL3/
  install.subdirs = true
}

build_config/file{*}: install = false
