import libs = libsdl3%lib{sdl3}

./: exe{audio-simple-playback}:          c{01-simple-playback/simple-playback}                   $libs
./: exe{audio-simple-playback-callback}: c{02-simple-playback-callback/simple-playback-callback} $libs
./: exe{audio-load-wav}:                 c{03-load-wav/load-wav}                                 $libs
./: exe{audio-multiple-streams}:         c{04-multiple-streams/multiple-streams}                 $libs
./: exe{audio-planar-data}:              c{05-planar-data/planar-data}                           $libs

c.poptions =+ "-I$out_root" "-I$src_root"

# Runtime resources upstream's own build copies next to these executables
# (upstream/examples/CMakeLists.txt DATAFILES).
#
exe{audio-load-wav}: file{sample.wav}: include = adhoc
exe{audio-multiple-streams}: file{sample.wav sword.wav}: include = adhoc

# Install next to the executables that use them.
#
file{sample.wav}@./: install = $install.bin
file{sword.wav}@./: install = $install.bin
