import libs = libsdl3%lib{sdl3}

./: exe{audio-simple-playback}:          c{01-simple-playback/simple-playback}                   $libs
./: exe{audio-simple-playback-callback}: c{02-simple-playback-callback/simple-playback-callback} $libs
./: exe{audio-load-wav}:                 c{03-load-wav/load-wav}                                 $libs
./: exe{audio-multiple-streams}:         c{04-multiple-streams/multiple-streams}                 $libs
./: exe{audio-planar-data}:              c{05-planar-data/planar-data}                           $libs

c.poptions =+ "-I$out_root" "-I$src_root"
